### ISSUE TITLE
POST /blogs/{blogId}/comments/{commentId}/like - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#14]
This method will make a comment as liked by current user. The author of comment cannot mark the his/her comment as liked.

**Comment by jeffdonthemic** [comment]
@sgodwin424 I merged your code for #24 but I can't get the test 2 run successfully. I'm not sure what I'm doing wrong but it looks like the code is say that `req.user` is null. Can you pull from the repo and see if you can get them to run? Thanks!!

**Comment by sgodwin424** [comment]
It looks like it's because the JWTs were changed from what the original commit. It would be fine, but I wasn't sure what username/handle the testConfig JWT was using. It looks like it's "kiko" (username) and "kiri4a" (username). Still though, the tests require two different JWTs (to simulate two different users).

I will make a commit.

**Comment by jeffdonthemic** [comment]
Your new code worked great! Sorry for screwing it up.
