### ISSUE TITLE
Add 200 mocha test for /api/secret

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#18]
Thanks for adding all of the test for you api routes! Awesome!! Can you add a quick test that other users can follow that shows how to return a 200 for /api/secret?

**Comment by ColorfullyMe** [comment]
@jeffdonthemic OK I can and will add this test but for the API to return 200 it requires valid JWT to be sent along with the request. This itself requires the test to have such token. It can be loaded from .env or config file but it has to provided for the test otherwise the /api/secret will return 401.

So how to approach this?

**Comment by jeffdonthemic** [comment]
@ColorfullyMe That sounds perfect!! Thanks.

**Comment by jeffdonthemic** [comment]
Sorry.. @ColorfullyMe I think I misunderstood your question. I think if you used a config file that would be fine. Does that answer your question?

**Comment by jeffdonthemic** [comment]
@ColorfullyMe Can you email me your topcoder handle so that I can pay you. jeff at appirio.com.

**Comment by kkartunov** [comment]
@jeffdonthemic It is: **kiri4a**

**Comment by kkartunov** [comment]
@jeffdonthemic Thank you!
