### ISSUE TITLE
POST /blogs - $50

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#3]
Creates a new blog record with the blog info submitted. This method should create a new slug based upon the title and default appropriate numeric fields (numOfUpVotes, etc) to 0.

**Comment by jeffdonthemic** [comment]
You can used [slugify](https://www.npmjs.com/package/slugify) to generate the slug when saving and ensure it is unique for that specific user. Two different users can have the same slug. So the following is OK:

jeffdonthemic - my-awesome-slug
mess - my-awesome-slug

**Comment by jiangzhihui** [comment]
Shall we just assign ourselves a issue then implement the feature and create a pull request after finish the code and test? Or will these issues be posted as challenges on Topcoder?

Thanks

**Comment by jeffdonthemic** [comment]
Yes @jiangzhihui !!! I just [posted this challenge](https://www.topcoder.com/challenge-details/30049557/?type=develop&noncache=true) (minutes ago) with information.

**Comment by mhikeo** [comment]
@jeffdonthemic I struggled to decide what can be handled for creating a new blog. To settle this, I made these assumptions on how POST /blogs will handle the input:
- There will be no comments yet since this is a new blog.
- _id for author have already been identified before calling this service. I assume blogger must be registered.
- For tags, _id for existing tags have already been identified and new ones must be added by this service.

**Comment by mhikeo** [comment]
@jeffdonthemic Hi. I made the fix for this ticket and created a pull request. Kindly verify. Thanks.

**Comment by jeffdonthemic** [comment]
@mhikeo , please see [this page on the wiki](https://github.com/topcoderinc/TopBlogger/wiki/API---Contributing#development). We are using bluebird for async operations.

**Comment by mhikeo** [comment]
@jeffdonthemic Sorry for the delay. I have created a new pull request. Kindly check. Thanks.

**Comment by jeffdonthemic** [comment]
Fixed by #38
